CREATE TABLE JoggingTime(
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 datetime DATETIME NOT NULL,
 distance DOUBLE NOT NULL,
 duration TIME NOT NULL,
 location VARCHAR(255) NOT NULL,
 weather VARCHAR(255),
 created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE User(
 id LONG PRIMARY KEY,
 role ENUM('regular', 'userManager', 'admin'),
 username VARCHAR(255) UNIQUE,
 password VARCHAR(255)  NOT NULL,
 created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMPx``
);

